openapi: 3.1.1
info:
  title: Generic ITI Job Posting
  version: 1.0.0
  description:
    Attribute schemas for generic ITI job posting (Item.attributes).
    These attributes are attached to Item.attributes to provide contextual 
    details of a generic ITI job posting made via onest jobstack.
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema

components:
  schemas:
    ########################################################################
    # ITEM.ATTRIBUTES — ITIJobPosting
    ########################################################################
    GenericITIJobPosting:
      type: object
      title: Generic ITI Job Posting
      description: Complete job posting form for Generic ITI positions
      properties:
        basicInfo:
          type: object
          title: Basic Information
          x-section: basic-info
          properties:
            jobProviderName:
              type: string
              title: Job Provider Name
              description: Enter job provider/company name
              minLength: 1
              pattern: "^\s*\S+\s*$"
            jobProviderType:
              type: string
              title: Job Provider Type
            jobProviderRegistration:
              type: string
              title: Job Provider Registration Details
              description: GST, CIN, TAN, PAN or other registration number
              minLength: 1
              pattern: "^.+$"
            jobProviderLocation:
              type: string
              title: Job Provider Location
              description: Enter job provider location
              minLength: 1
              pattern: "^\s*\S+\s*$"
            jobProviderLogo:
              type: string
              title: Job Provider Logo
              format: data-url
          required:
            - jobProviderName
            - jobProviderLocation

        jobDetails:
          type: object
          title: Job Details
          x-section: job-details
          properties:
            callBackTime:
              type: string
            title:
              type: string
              minLength: 1
              pattern: "^\s*\S+\s*$"
            designation:
              type: string
              minLength: 1
              pattern: "^\s*\S+\s*$"
            jobType:
              type: array
              items:
                type: string
                enum: [Full-time, Part-time, Apprenticeship]
              minItems: 1
              uniqueItems: true
            hiringUrgency:
              type: string
            hiringManagerName:
              type: string
            hiringManagerDesignation:
              type: string
            validTill:
              type: string
              format: date
            positions:
              type: integer
              minimum: 1
              default: 1
            jobDetailsVideo:
              type: string
              format: data-url
            jobDescription:
              type: string
              minLength: 10
              maxLength: 2000
            jobLocationPhotos:
              type: array
              items:
                type: string
                format: data-url
            workingHoursPerDay:
              type: number
              minimum: 1
              maximum: 24
            modeOfWork:
              type: array
              items:
                type: string
                enum: [on-site-no-shift, on-site-shifts, remote, hybrid, travelling]
              minItems: 1
              uniqueItems: true
            minMonthlyInHand:
              type: number
            maxMonthlyInHand:
              type: number
            monthlyAttendanceBonus:
              type: number
            monthlyAttendanceBonusCriteria:
              type: string
            monthlyAverageOT:
              type: string
            otPerHourRate:
              type: number
            monthlyPfEsicBenefits:
              type: number
            foodProvided:
              type: string
              enum: [yes, no]
            travelProvided:
              type: string
          required:
            - title
            - positions

        jobNeeds:
          type: object
          title: Job Needs
          x-section: job-needs
          properties:
            ageAllowedLowerLimit:
              type: integer
              minimum: 18
              maximum: 100
            ageAllowedUpperLimit:
              type: integer
              minimum: 18
              maximum: 100
            genderPreference:
              type: string
              enum: [Male, Female, Other, No Preference]

            educationSubsection:
              type: object
              title: Education Qualification
              properties:
                minEducationLevel:
                  type: array
                  items:
                    type: string
                    enum: ["10th Pass", "12th Pass", "ITI", "Diploma", "Graduate", "Other"]
                  minItems: 1
                  uniqueItems: true
                itiSpecialtyPreference:
                  type: array
                  items:
                    type: string
                    enum:
                      - Additive Manufacturing Technician Three D Painting
                      - Additive Manufacturing Technician Three D Printing (NSQF)
                      - ADVANCED CNC MACHINING TECHNICIAN (NSQF)
                      - OTHER
                  minItems: 1
                  uniqueItems: true
                skillsRequired:
                  type: string

            languagesSubsection:
              type: object
              title: Languages
              properties:
                languagesKnown:
                  type: array
                  items:
                    type: string
                    enum:
                      - Assamese
                      - Bengali
                      - Bodo
                      - Dogri
                      - English
                      - Gujarati
                      - Hindi
                      - Kannada
                      - Kashmiri
                      - Konkani
                      - Maithili
                      - Malayalam
                      - Manipuri
                      - Marathi
                      - Mizo
                      - Nepali
                      - Odia
                      - Punjabi
                      - Sanskrit
                      - Santali
                      - Sindhi
                      - Tamil
                      - Telugu
                      - Urdu
                  minItems: 1
                  uniqueItems: true
