openapi: 3.1.1
info:
  title: In-Store Promoter Job Posting Schema
  version: 1.0.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
x-jsonld-context:
  '@context': {}
components:
  schemas:
    InStorePromoterJobPosting:
      allOf:
        - $ref: '../generic-job-schema/attribute.yaml#/components/schemas/GenericJobPostingBase'
        - type: object
          title: 'In-Store Promoter Job Posting (Extension)'
          properties:
            inStorePromoterRequirements:
              type: object
              title: 'In-Store Promoter Requirements'
              x-section: 'in-store-promoter-requirements'
              properties:
                languagesKnown:
                  type: array
                  title: 'Languages Known'
                  description: 'Languages the promoter must know'
                  items:
                    type: string
                    enum:
                      - Assamese
                      - Bengali
                      - Bodo
                      - Dogri
                      - English
                      - Gujarati
                      - Hindi
                      - Kannada
                      - Kashmiri
                      - Konkani
                      - Maithili
                      - Malayalam
                      - Manipuri
                      - Marathi
                      - Mizo
                      - Nepali
                      - Odia
                      - Punjabi
                      - Sanskrit
                      - Santali
                      - Sindhi
                      - Tamil
                      - Telugu
                      - Urdu
                  minItems: 1
                  uniqueItems: true
                # QUALIFICATION
                highestQualification:
                  type: array
                  title: 'Minimum Highest Qualification Preferred'
                  items:
                    type: string
                    enum:
                      - '10th'
                      - '12th'
                      - '3 year Undergraduate Degree'
                      - '4 year Undergraduate Degree'
                      - 'Postgraduate and above'
                  uniqueItems: true
                  minItems: 1
                presentabilityScore:
                  type: string
                  title: 'Presentability Score'
                  description: 'Minimum acceptable presentability score'
                communicationSkillScore:
                  type: string
                  title: 'Communication Skill Score'
                  description: 'Minimum acceptable communication skill score'
                domainKnowledge:
                  type: array
                  title: 'Domain Knowledge'
                  description: 'Select domain knowledge areas'
                  items:
                    type: string
                    enum:
                      - 'general'
                      - 'cashcards'
                      - 'electronics'
                      - 'mobile-phones'
                      - 'kitchen-appliances'
                      - 'furniture'
                      - 'other'
                  uniqueItems: true
                  minItems: 1
                ageAllowedLowerLimit:
                  type: integer
                  minimum: 18
                  maximum: 100
                ageAllowedUpperLimit:
                  type: integer
                  minimum: 18
                  maximum: 100
              required:
                - highestQualification
                - domainKnowledge
                - languagesKnown
          required:
            - inStorePromoterRequirements
    # Beckn Item.attributes wrapper
    Attribute:
      type: object
      properties:
        workOpportunity:
          $ref: '#/components/schemas/InStorePromoterJobPosting'
